apiVersion: v1
kind: Pod

metadata:
  name: mon_projet_hetic
  labels:
    app: web

spec:
  containers:
  - name: mariadb
    image: mariadb:latest
    ports:
    - containerPort:3306

  - name: phpmyadmin
    image: phpmyadmin
    ports:
    - containerPort:40001

  - name: wordpress
    image: wordpress
    ports:
    - containerPort:8080

  - name: web
    image: web
    ports:
    -containerPort:80